spring:
  application:
    name: inventory-service
  data:
    mongodb:
      database: ${MONGODB_DATABASE:salary-management-inventory}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin}
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}?authSource=admin
      host: ${MONGO_DB_HOST:localhost}
  docker:
    compose:
      enabled: false
