server:
  port: 9100

eureka:
  client:
    service-url:
      host: ${EUREKA_HOST:localhost}
      port: ${EUREKA_PORT:8761}
      defaultZone: http://${eureka.client.service-url.host}:${eureka.client.service-url.port}/eureka/

management:
  server:
    port: 9101
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      database: ${MONGODB_DATABASE:salary-management-inventory}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin}
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}?authSource=admin
      host: ${MONGO_DB_HOST:localhost}
  docker:
    compose:
      enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  file:
    path: ./logs
    name: ${spring.application.name}
