spring:
  docker:
    compose:
      enabled: true
      file: ./salary-management-inventory-service/compose.yml
  graphql:
    graphiql:
      enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
